### ISSUE TITLE
Bug - Settings get reset using version control

### ISSUE THREAD

**Issue by Timelapser** [WooshiiDev/HierarchyDecorator#45] opened 2021-12-02 14:20 UTC
**Describe the bug**
When opening a project on a new PC after pulling from a repo: "HierarchyDecorator version changed, updating cached components." will get triggered and overrides the settings asset.

The workaround is to simply revert changes on the settings asset, but it would be great to have a way to retain settings when already present (but when likely no previous version check has been done yet).

**Comment by WooshiiDev** [comment] 2022-01-09 09:49
Hi Timelapser, 
apologies for the long month delay for a reply, December became very busy for me and I had to focus on other work 🙂 

I've been looking into this and finally found out the cause of the issue. The main cause was due to attempts to find the Settings Scriptable before it had been cached by the [AssetDatabase](https://docs.unity3d.com/ScriptReference/AssetDatabase.html). This has now been fixed and the changes can be seen [here](https://github.com/WooshiiDev/HierarchyDecorator/blob/v0.8.5/HierarchyDecorator/Scripts/Editor/HierarchyDecorator.cs#L34).

Along with this, I've updated some of the save data so it's project specific, as the ID saved for the settings asset used for Hierarchy Decorator was not per project. This has now been changed. 

If this issue still persists afterwards, then please do not hesitate to reply to this issue. 
I'll be keeping this open until I release [v0.8.5 ](https://github.com/WooshiiDev/HierarchyDecorator/tree/v0.8.5) but you can check out the branch directly if you're interested.

**Comment by Timelapser** [comment] 2022-01-09 22:20
Hi,

Don't worry - thanks so much for taking a look at it and fixing it! I'll try it out and make sure to let you know if anything else occurs.

Thanks again! Really been enjoying the super clean hierarchies :)

**Comment by WooshiiDev** [comment] 2022-01-17 13:59
Hi there Timelapser, I've released the fix to [v0.8.5](https://github.com/WooshiiDev/HierarchyDecorator/releases/tag/v0.8.5). 🙂 
From my testing this should be fixed and I'll be closing the issue for the time being, however if this is not the case I'll be setting this bug to high priority and I'll get on it right away.

**Closed by WooshiiDev** 2022-01-17 13:59 UTC
Labels: bug, High Priority
