### ISSUE TITLE
Bug: Parent Transform dropdown arrow disappears in Context-sensitive Prefab Mode

### ISSUE THREAD

**Issue by Medallyon** [WooshiiDev/HierarchyDecorator#24] opened 2021-08-09 09:53 UTC
Unity Version 2020.3.0

**Describe the bug**
Parent Transform dropdown arrow disappears in Context-sensitive Prefab Mode.

**To Reproduce (If applicable)**

1. Create a new prefab
2. Create some objects in the prefab
3. Give the last object in the prefab one or more children
4. Drag the Prefab into the scene and open it in context-sensitive mode
5. The last object (containing some children) does not appear to have any children, and can only be opened with Right Arrow

**Comment by WooshiiDev** [comment] 2021-08-09 14:50
Ah I can't believe this got past me...
Will fix this later today, shouldn't take too long.

Due to how I handle checks for drawing the foldouts again, I think I know what the issue is

Cheers,
Wooshii

**Comment by WooshiiDev** [comment] 2021-08-12 01:03
This should be fixed in [v0.7.1.0](https://github.com/WooshiiDev/HierarchyDecorator/releases/tag/v0.7.1.0) 🙂 

If there are any follow up issues with foldouts I'll reopen this with a link to the created issues.

Thanks,
Wooshii

**Closed by WooshiiDev** 2021-08-12 01:03 UTC
Labels: bug
