### ISSUE TITLE
Changing Category Properties doesn't seem to have any effect

### ISSUE THREAD

**Issue by Medallyon** [WooshiiDev/HierarchyDecorator#18] opened 2021-08-03 14:26 UTC
I've tried changing header colours and other properties, but they don't seem to have any effect on any categories in the hierarchy. I've tried to rename the transform, create a new transform, and even switching scenes. There are no associated errors as far as I can tell.

![image](https://user-images.githubusercontent.com/17483199/128032405-14fd37f6-bb59-4274-a617-beacf5090c0d.png)

**Comment by WooshiiDev** [comment] 2021-08-04 23:23
This is caused by how the Scriptable saves. 
A lot of the data issues come from switching between `SerializedProperty` and directly setting data in Editor scripts. There are workarounds to use both but they're not great.  

This has been fixed in the upcoming release but I should have sorted this earlier, apologies. Does the most recent [release](https://github.com/WooshiiDev/HierarchyDecorator/releases) have this issue too?

**Comment by Medallyon** [comment] 2021-08-06 14:06
> Does the most recent release have this issue too?

I just installed it via upm/git, so I'd assume I'm on the latest release.

**Comment by WooshiiDev** [comment] 2021-08-08 22:04
Issues to do with saving settings without them reverting or even applying at all were throughout all of the project. These have now been fixed in [Hierarchy Decorator v0.7](https://github.com/WooshiiDev/HierarchyDecorator/releases/tag/0.7.0.0) that has just been released.

**Closed by WooshiiDev** 2021-08-08 22:04 UTC
Labels: bug
