### ISSUE TITLE
Icon  to signify MonoBehaviour/Scripts

### ISSUE THREAD

**Issue by MostHated** [WooshiiDev/HierarchyDecorator#5] opened 2020-09-14 22:52 UTC
Hey there,
   I was going through the icons but I didn't see any icon signifying whether or not an object has scripts on them or not. Is it possible to include one? That is honestly one of the most useful, to me at least. Even better yet would be a script icon and a small number on it to show how many scripts an object has, but simply having just a single script icon would be great.

Thanks,
-MH

**Comment by WooshiiDev** [comment] 2020-09-17 09:26
(Sorry for the slow reply in advance)
Hey there @MostHated 👋 ,

fun fact, that I technically had this prior to uploading before the system was more structured.
Interestingly, I was curious myself why that's not appearing on the list of icon selections and it was prior. It does get recognized by the types within the Unity Assemblies, so I assume I've done something *slightly* different in my old versions.

I'll be having a look at the older versions I have offline and seeing what the cause is, I'll follow up after I've done so
Thanks,
Wooshii ~

**Comment by WooshiiDev** [comment] 2020-09-19 02:00
Well hello @MostHated,

I've added functionality for MonoBehaviour icons, that will:

 - Allows a global toggle for all script icons to be on or off (and will show their custom icon if they have one)
 - Will also allow you to add custom icons manually if a global option is not preferred.

The custom icons can be selected/added in the "Custom" option in the Icons Tab.
The GUI is a little unrefined right now but I'll be working on refining the entire GUI as some here and there isn't the best standard. 

[Redesign of GUI Card](https://github.com/WooshiiDev/HierarchyDecorator/projects/1#card-45785911)

**Comment by MostHated** [comment] 2020-09-19 04:23
Heya,
    I saw that it finally showed up on OpenUPM a little while ago from my RSS feed, so I had just installed it from there a little bit ago and saw the icons straight away. I had not thought much of it, but now that you mention it custom icons could end up being pretty nice. Especially considering how many hours (days/weeks/months/years even) that I spend in Unity, lol. I might have to give that a try. 

👍 Thanks again, much appreciated.
-MH

**Comment by WooshiiDev** [comment] 2020-09-19 12:32
Issue Fix, closing issue \o.

**Closed by WooshiiDev** 2020-09-19 12:32 UTC
